spring.application.name=HADES_COMMUNICATION_SECURITY_BACKEND

spring.rabbitmq.host=leopard-01.lmq.cloudamqp.com
spring.rabbitmq.port=5672
spring.rabbitmq.username=cwyxvdym
spring.rabbitmq.password=l_jEm48sdg5HvVkQNXPTpkQfd0tn4xKy
spring.rabbitmq.virtual-host=cwyxvdym

spring.rabbitmq.requested-heartbeat=10
spring.rabbitmq.connection-timeout=5000

### Conexión base de datos MongoDB (No relacional)

spring.data.mongodb.uri=${MONGO_URI:mongodb+srv://JuanCaballero:Isabella2004@clustersirha.pc6me39.mongodb.net/sirha?retryWrites=true&w=majority&appName=ClusterSirha}
spring.data.mongodb.database=rideci

spring.websocket.enabled=true
server.ssl.enabled=false
spring.web.resources.add-mappings=false

server.forward-headers-strategy=none
server.http2.enabled=false


